const PERS0N_DELETE_SUCCESS = 'PERS0N-DELETE-SUCCESS'
const PERSON_ID_NOT_FOUND = 'PERSON-ID-NOT-FOUND'
const REQUIRED_FIELDS_MISSING = 'REQUIRED-FIELDS-MISSING'

module.exports = { PERS0N_DELETE_SUCCESS, PERSON_ID_NOT_FOUND, REQUIRED_FIELDS_MISSING }
